"""create permissions table

Revision ID: 3e441382ac01
Revises: 22bc5f600cb4
Create Date: 2026-05-20 00:55:10.125085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e441382ac01'
down_revision = '22bc5f600cb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('trade_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('site',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('zip_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('street',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('street_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('neighborhood',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('neighborhood',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('street_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('street',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('zip_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('site',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('trade_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    op.drop_table('permissions')
    # ### end Alembic commands ###
