# Salva os dados no disco a cada 60 segundos se houver mudanças
save 60 1

# Tamanho máximo de memória
maxmemory 256mb

# Quando atingir o limite, remove as chaves menos usadas
maxmemory-policy allkeys-lru

# Log level
loglevel notice